using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using System.IO;

namespace Castara.Wpf.Diagnostics.CrashReport;

/// <summary>
/// View model for the crash report dialog that allows users to review crash details
/// and choose whether to save locally and/or send to the diagnostic server.
/// </summary>
/// <remarks>
/// This view model uses CommunityToolkit.Mvvm source generators to automatically generate
/// property change notifications and commands. The [ObservableProperty] attribute generates
/// public properties with INotifyPropertyChanged implementation.
/// 
/// <para>
/// <b>User Options:</b>
/// </para>
/// <list type="bullet">
/// <item><description>Save crash report locally to AppData folder</description></item>
/// <item><description>Send crash report to diagnostic server (if enabled)</description></item>
/// <item><description>Copy report JSON to clipboard</description></item>
/// <item><description>Close without taking action</description></item>
/// </list>
/// </remarks>
public partial class CrashReportDialogViewModel : ObservableObject
{
    /// <summary>
    /// Backing field for the SendReport property (auto-generated by CommunityToolkit.Mvvm).
    /// Gets or sets a value indicating whether the crash report should be sent to the diagnostic server.
    /// </summary>
    [ObservableProperty]
    private bool sendReport = false;

    /// <summary>
    /// Backing field for the SaveLocally property (auto-generated by CommunityToolkit.Mvvm).
    /// Gets or sets a value indicating whether the crash report should be saved to the local file system.
    /// Defaults to true to ensure reports are preserved even if upload fails.
    /// </summary>
    [ObservableProperty]
    private bool saveLocally = true;

    /// <summary>
    /// Gets a value indicating whether crash report upload functionality is enabled.
    /// When false, the "Send Report" option is disabled in the UI.
    /// </summary>
    /// <remarks>
    /// This value is typically controlled by application configuration (appsettings.json)
    /// and allows disabling the upload feature without removing the code.
    /// </remarks>
    public bool IsCrashReportUploadEnabled { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="CrashReportDialogViewModel"/> class.
    /// </summary>
    /// <param name="reportJson">The crash report data in JSON format.</param>
    /// <param name="reportId">The unique identifier for this crash report (typically a GUID).</param>
    /// <param name="isCrashReportUploadEnabled">Whether crash report upload functionality is enabled.</param>
    /// <exception cref="ArgumentNullException">
    /// Thrown when <paramref name="reportJson"/> or <paramref name="reportId"/> is null.
    /// </exception>
    public CrashReportDialogViewModel(string reportJson, string reportId, bool isCrashReportUploadEnabled)
    {
        ReportJson = reportJson ?? throw new ArgumentNullException(nameof(reportJson));
        ReportId = reportId ?? throw new ArgumentNullException(nameof(reportId));
        IsCrashReportUploadEnabled = isCrashReportUploadEnabled;

        LocalSaveDirectory = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "Castara",
            "CrashReports");

        LocalSaveFileName = $"{ReportId}.json";

        CloseCommand = new RelayCommand(Close);
        ContinueCommand = new RelayCommand(Continue);
        CopyCommand = new RelayCommand(Copy);
        CopySavePathCommand = new RelayCommand(CopySavePath);
    }

    public string ReportId { get; }

    public string ReportJson { get; }

    public string Title => "Castara encountered an unexpected error";

    public string Message =>
        "Castara ran into an unexpected problem and needs to close. " +
        "You can review the diagnostic report below and choose whether to save or send it for analysis.";

    public string LocalSaveDirectory { get; }

    public string LocalSaveFileName { get; }

    public string LocalSavePath => Path.Combine(LocalSaveDirectory, LocalSaveFileName);

    public bool HasPrimaryAction => SendReport || SaveLocally;

    public string PrimaryActionText =>
        (SaveLocally, SendReport) switch
        {
            (true, true) => "Save, Send and Close",
            (true, false) => "Save and Close",
            (false, true) => "Send and Close",
            _ => string.Empty
        };

    public IRelayCommand CloseCommand { get; }

    public IRelayCommand ContinueCommand { get; }

    public IRelayCommand CopyCommand { get; }

    public IRelayCommand CopySavePathCommand { get; }

    public event EventHandler<bool>? CloseRequested;

    public event EventHandler<string>? CopyRequested;

    partial void OnSendReportChanged(bool value)
    {
        OnPropertyChanged(nameof(HasPrimaryAction));
        OnPropertyChanged(nameof(PrimaryActionText));
    }

    partial void OnSaveLocallyChanged(bool value)
    {
        OnPropertyChanged(nameof(HasPrimaryAction));
        OnPropertyChanged(nameof(PrimaryActionText));
    }

    private void Close() => CloseRequested?.Invoke(this, false);

    private void Continue() => CloseRequested?.Invoke(this, true);

    private void Copy() => CopyRequested?.Invoke(this, ReportJson);

    private void CopySavePath() => CopyRequested?.Invoke(this, LocalSavePath);
}