namespace Castara.Web.Api.Dtos.Diagnostics.Responses;

/// <summary>
/// Represents the result of a crash report storage operation, including server-generated metadata
/// for tracking and correlation.
/// </summary>
/// <param name="IncidentId">The server-generated unique incident identifier for this crash report.</param>
/// <param name="ReceivedAtUtc">The UTC timestamp when the crash report was received and processed by the server.</param>
/// <param name="Status">The storage status (e.g., "Stored", "Queued", "Failed", "Ignored").</param>
/// <remarks>
/// The <paramref name="IncidentId"/> is generated by the server and may differ from the client's
/// original report ID. Both IDs should be logged for correlation purposes.
/// </remarks>
public sealed record StoreCrashReportResultDto(
    string IncidentId,
    DateTimeOffset ReceivedAtUtc,
    string Status);
