// <auto-generated />
using System;
using Castara.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Castara.Infrastructure.Migrations
{
    [DbContext(typeof(CastaraDbContext))]
    partial class CastaraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("Castara.Infrastructure.Persistence.Entities.CompositionProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Carbon")
                        .HasColumnType("REAL");

                    b.Property<double>("Chromium")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Manganese")
                        .HasColumnType("REAL");

                    b.Property<double>("Molybdenum")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Nickel")
                        .HasColumnType("REAL");

                    b.Property<double>("Phosphorus")
                        .HasColumnType("REAL");

                    b.Property<double>("Silicon")
                        .HasColumnType("REAL");

                    b.Property<double>("Sulfur")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("composition_profiles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
