using Castara.Web.Api.Dtos.Diagnostics.Requests;

namespace Castara.Web.Api.Services.Diagnostics;

/// <summary>
/// Defines a contract for storing sanitized crash reports after they have been validated and processed.
/// </summary>
/// <remarks>
/// <para>
/// Implementations of this interface handle the actual persistence of crash reports to various storage backends
/// such as JSON files, databases, cloud storage services, or logging/telemetry platforms.
/// </para>
/// <para>
/// The storage strategy can be configured and swapped at runtime, allowing different storage implementations
/// for development, staging, and production environments. Common implementations include:
/// </para>
/// <list type="bullet">
/// <item><description><c>NullCrashReportStorageService</c> - Discards reports (used when ingestion is disabled)</description></item>
/// <item><description><c>JsonFileCrashReportStorageService</c> - Stores reports as JSON files on disk</description></item>
/// <item><description><c>DatabaseCrashReportStorageService</c> - Persists reports to a database</description></item>
/// <item><description><c>CloudCrashReportStorageService</c> - Uploads reports to cloud storage (Azure Blob, S3, etc.)</description></item>
/// </list>
/// </remarks>
public interface ICrashReportStorageService
{
    /// <summary>
    /// Asynchronously stores a sanitized crash report and returns metadata about the storage operation.
    /// </summary>
    /// <param name="request">The crash report submission request to store. Should be pre-validated and sanitized.</param>
    /// <param name="cancellationToken">Cancellation token for async operations.</param>
    /// <returns>
    /// A task that represents the asynchronous operation. The task result contains metadata about the
    /// stored report, including the server-generated incident ID and storage status.
    /// </returns>
    /// <remarks>
    /// <para>
    /// This method assumes that the request has already been:
    /// </para>
    /// <list type="number">
    /// <item><description>Validated for HMAC signature authenticity</description></item>
    /// <item><description>Sanitized to remove sensitive user information</description></item>
    /// </list>
    /// <para>
    /// Implementations should handle storage failures gracefully and return appropriate status information
    /// in the result. The incident ID should be unique and can be used to correlate the client's report ID
    /// with the server-side storage location.
    /// </para>
    /// </remarks>
    Task<StoreCrashReportResult> StoreAsync(
        SubmitCrashReportRequest request,
        CancellationToken cancellationToken);
}

/// <summary>
/// Represents the result of a crash report storage operation, including server-generated metadata
/// for tracking and correlation.
/// </summary>
/// <param name="IncidentId">The server-generated unique incident identifier for this crash report.</param>
/// <param name="ReceivedAtUtc">The UTC timestamp when the crash report was received and processed by the server.</param>
/// <param name="Status">The storage status (e.g., "Stored", "Queued", "Failed", "Ignored").</param>
/// <remarks>
/// The <paramref name="IncidentId"/> is generated by the server and may differ from the client's
/// original report ID. Both IDs should be logged for correlation purposes.
/// </remarks>
public sealed record StoreCrashReportResult(
    string IncidentId,
    DateTimeOffset ReceivedAtUtc,
    string Status);
